# Generated by Django 5.1.1 on 2024-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
